name: Docker Compose Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        run: |
          echo "SERVER_ADDR=localhost" > .env
          echo "SERVER_PORT=8080" >> .env

      - name: Build Docker Compose
        run: docker compose up --build -d

      - name: Wait for Containers to Start
        run: sleep 30 # 30 seconds for startup

      - name: Check Container Logs
        run: docker logs $(docker compose ps -q cpp_victory)

      - name: Stop and Remove Containers
        run: docker compose down
